## DEV CONFIG

"%dev":
  quarkus:

    # AUTHORIZATION
    oauth2:
      client-id: 3lmySWpwg2nPc8WXy8jldGMO9iB0Slf7
      client-secret: jvLMKxktdCNosV62MfD1B06EzU5YSXkpiqs9PDb3B6mIH5iHO2tl-rwlrjtCnn8J
      introspection-url: https://fino-test.eu.auth0.com/api/v2/

    oidc:
      auth-server-url: https://fino-test.eu.auth0.com
      token:
        issuer: https://fino-test.eu.auth0.com/
      application-type: web-app
      client-id: 3lmySWpwg2nPc8WXy8jldGMO9iB0Slf7s
      credentials:
        secret: jvLMKxktdCNosV62MfD1B06EzU5YSXkpiqs9PDb3B6mIH5iHO2tl-rwlrjtCnn8J

    http:
      ssl:
        certificate:
          file: ssl/localhost.crt
          key-file: ssl/localhost.key
    # PERSISTENCE
    datasource:
      url: jdbc:postgresql://localhost:5432/fino-dev-db
      driver: org.postgresql.Driver
      username: postgres
      password: postgres
    hibernate-orm:
      sql-load-script: import-dev.sql
      database:
        generation: drop-and-create  # drop and create the database at startup (use `update` to only update the schema)


## TEST CONFIG

"%test":
  quarkus:

    # PERSISTENCE
    datasource:
      url: jdbc:h2:tcp://localhost/mem:test
      driver: org.h2.Driver
    hibernate-orm:
#      sql-load-script: import-dev.sql
      database:
        generation: drop-and-create
