## DEV CONFIG

"%dev":
  quarkus:
    # ENABLE HTTPS
    http:
      ssl:
        certificate:
          file: ssl/localhost.crt
          key-file: ssl/localhost.key
      cors:
        ~: true
        methods: GET,PUT,POST,DELETE
        origins: https://localhost:4200,https://honeypot.lan:4200,https://littlehoneypot:4200
        headers: origin,content-type,accept,authorization
        access-control-max-age: 1
    # PERSISTENCE
    datasource:
      url: jdbc:postgresql://localhost:5432/fino-dev-db
      driver: org.postgresql.Driver
      username: postgres
      password: postgres
    hibernate-orm:
      sql-load-script: import-dev.sql
      database:
        generation: drop-and-create  # drop and create the database at startup (use `update` to only update the schema)
  mp:
    # JWT VERIFICATION
    jwt:
      verify:
        publickey:
          location: https://fino-test.eu.auth0.com/.well-known/jwks.json
        issuer: https://fino-test.eu.auth0.com/


## PROD CONFIG

"%prod":
  quarkus:
    # PERSISTENCE
    datasource:
      url:
      driver: org.postgresql.Driver
      username:
      password:
    hibernate-orm:
      database:
        generation: create
  mp:
    # JWT VERIFICATION
    jwt:
      verify:
        publickey:
          location:
        issuer:


## TEST CONFIG

"%test":
  quarkus:

    # PERSISTENCE
    datasource:
      url: jdbc:h2:tcp://localhost/mem:test
      driver: org.h2.Driver
    hibernate-orm:
#      sql-load-script: import-dev.sql
      database:
        generation: drop-and-create
